/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Task {
  'id' : TaskId,
  'status' : TaskStatus,
  'completedAt' : [] | [bigint],
  'title' : string,
  'proofText' : [] | [string],
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'durationMinutes' : bigint,
  'proofImage' : [] | [ExternalBlob],
}
export type TaskId = bigint;
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'locked' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string, string, bigint], TaskId>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTaskIds' : ActorMethod<[], Array<TaskId>>,
  'getCompletedTasks' : ActorMethod<[], Array<Task>>,
  'getLockedTaskIds' : ActorMethod<[], Array<TaskId>>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getPendingTasks' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[TaskId], [] | [Task]>,
  'getTasksByTimeRange' : ActorMethod<[bigint, bigint], Array<Task>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'startFocusSession' : ActorMethod<[TaskId], undefined>,
  'submitProof' : ActorMethod<
    [TaskId, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];