/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'locked' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'proofText' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'proofImage' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [TaskId], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTaskIds' : IDL.Func([], [IDL.Vec(TaskId)], ['query']),
  'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getLockedTaskIds' : IDL.Func([], [IDL.Vec(TaskId)], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getPendingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getTasksByTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'startFocusSession' : IDL.Func([TaskId], [], []),
  'submitProof' : IDL.Func(
      [TaskId, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'locked' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'proofText' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'proofImage' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [TaskId], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTaskIds' : IDL.Func([], [IDL.Vec(TaskId)], ['query']),
    'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getLockedTaskIds' : IDL.Func([], [IDL.Vec(TaskId)], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getPendingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getTasksByTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'startFocusSession' : IDL.Func([TaskId], [], []),
    'submitProof' : IDL.Func(
        [TaskId, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };